print("Personal Survey")
name = input("What is your name? ")
food = input("What is yout favorite food? ")
hobby = input("What is that one thing you like to do? ")
motive = input("What is your motivation to learn Python? ")
print("Hello! " + name + ". Thanks for sharing the Survey answers.")
print("As you mentioned your favorite food as " + food + ", I wanted to know what type of " + food + " is your favorite? 😅 JK! ")
print("And your hobby " + hobby + ", fr that's insane. Like?? Hello??? That's 🔥 ")
print("And yeahh, you are too frank on your motive though 😂 " + motive + " Like that is everyone's motive I guess so 😅 ")
print("Well, Thank You for talking with us." "You will receive additional info on your mail!")
print("\n Please drop out your mail, so that we can reachout to you.")
mail = input("Enter email address: ")
print("\n Thank You! ")