text = input("Enter a sentence: ")
print("\n String Analysis: ")
print("Lowercase: ", text.lower())
print("Uppercase: ", text.upper())
print("Title Case: ", text.title())
print("Word Count: ", len(text.split()))
print("First Character: ", text[0])
print("Last Character: ", text[-1])
print("Is it a question?", text.strip().endswith("?"))